---
# lifecycle processing for all datasets currently being tracked

name: Dataset Lifecycle

# TODO: add a trigger for a card moved on a project?
# want to be able to make guarantees around a single action at a time
# I *think* this is guaranteed with only a single runner
on:
  schedule:
    # run at around noon PST
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  exec-lifecycle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure conda
        shell: bash
        run: |
          . devtools/gh-actions/initialize_conda.sh
          conda activate
          conda config --set always_yes yes
          conda config --add channels conda-forge
          conda install --quiet qcportal PyGithub pandas tabulate
          conda info --all
          conda list

      - name: Run lifecycle processing script
        shell: bash
        env: # Or as an environment variable
          GH_TOKEN: ${{ secrets.GH_DANGERBOT_TOKEN_LIMITED}}
        run: |
            . devtools/gh-actions/initialize_conda.sh
            conda activate
            python ./management/lifecycle.py
