name: Dataset Validation


on:
  pull_request:
    branches:
      - "master"

jobs:
  dataset_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1
      - name: Configure conda
        with:
          python-version: 3.7
          activate-enviroment: validation
          environment-file: devtools/conda-envs/validation.yaml
          auto-activate-base: false

      - name: Addtional info about the build
        shell: bash
        run: |
          uname -a
          df -a
          ulimit -a

      - name: Enviroment Information
        shell: bash
        run: |
          conda info
          conda list

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: Gather new datasets

      - name: Validate Dataset Entries
        shell: bash
        env: # Or as an environment variable
          GH_TOKEN: ${{ secrets.GH_DANGERBOT_TOKEN_LIMITED}}
        run: |
          python ./management/validation.py '${{ steps.file_changes.outputs.files}}' '${{ github.event.number }}'


