name: Dataset Validation

# TODO: add a trigger for a card moved on a project?
# want to be able to make guarantees around a single action at a time
# I *think* this is guaranteed with only a single runner
on:
  pull_request:
    branches:
      - "master"

jobs:
  dataset_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure conda
        shell: bash
        run: |
          . devtools/gh-actions/initialize_conda.sh
          conda activate
          conda config --set always_yes yes
          conda install --quiet -c conda-forge -c omnia/label/rc -c omnia -c openeye qcsubmit
          conda info --all
          conda list
          pip install basis_set_exchange

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: Gather new datasets
        run: |
          python ./managment/validation.py '${{ steps.file_changes.outputs.files}}'


